# Generated by Django 3.0.4 on 2023-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
