# Generated by Django 3.0.4 on 2023-12-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_developers_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developers',
            new_name='Developer',
        ),
    ]
