# Generated by Django 3.0.4 on 2024-01-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20240107_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='chat_count',
            field=models.IntegerField(default=0),
        ),
    ]
